<a href="https://colab.research.google.com/github/ryukios/stat_ML/blob/main/variancia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import statistics
from scipy import stats
import math

In [4]:
dados = np.array([150, 151, 152, 152, 153, 154, 155, 155, 155, 155, 156, 156, 156,
       157, 158, 158, 160, 160, 160, 160, 160, 161, 161, 161, 161, 162,
       163, 163, 164, 164, 164, 165, 166, 167, 168, 168, 169, 170, 172,
       173])

In [5]:
dados.max() - dados.min()

np.int64(23)

In [7]:
q1 = np.quantile(dados, 0.25)
q3 = np.quantile(dados, 0.75 )
q1, q3

(np.float64(155.75), np.float64(164.0))

In [8]:
diferenca_interquartil = q3 - q1
diferenca_interquartil

np.float64(8.25)

In [10]:
inferior = q1 - (1.5 * diferenca_interquartil)
superior = q3 + (1.5 * diferenca_interquartil)
print(inferior)
print(superior)

143.375
176.375


In [11]:
odd_numbers = dados[dados % 2 != 0]
display(odd_numbers)

array([151, 153, 155, 155, 155, 155, 157, 161, 161, 161, 161, 163, 163,
       165, 167, 169, 173])

In [12]:
media = odd_numbers.sum() / len(odd_numbers)
media

np.float64(160.2941176470588)

In [15]:
desvio = abs(odd_numbers - media)
desvio

array([ 9.29411765,  7.29411765,  5.29411765,  5.29411765,  5.29411765,
        5.29411765,  3.29411765,  0.70588235,  0.70588235,  0.70588235,
        0.70588235,  2.70588235,  2.70588235,  4.70588235,  6.70588235,
        8.70588235, 12.70588235])

In [16]:
desvio = desvio ** 2
desvio

array([ 86.38062284,  53.20415225,  28.02768166,  28.02768166,
        28.02768166,  28.02768166,  10.85121107,   0.4982699 ,
         0.4982699 ,   0.4982699 ,   0.4982699 ,   7.32179931,
         7.32179931,  22.14532872,  44.96885813,  75.79238754,
       161.43944637])

In [17]:
soma_desvio = desvio.sum()
soma_desvio

np.float64(583.5294117647059)

In [25]:
variancia = soma_desvio / (len(odd_numbers))
variancia

np.float64(34.325259515570934)

In [23]:
def get_variancia(dataset):
  media = dataset.sum() / len(dataset)
  desvio = abs(dataset - media)
  desvio = desvio ** 2
  soma_desvio = desvio.sum()
  return soma_desvio / (len(dataset))


In [24]:
get_variancia(odd_numbers)


np.float64(34.325259515570934)

In [22]:
np.var(odd_numbers)

np.float64(34.325259515570934)

In [26]:
statistics.variance(odd_numbers)

np.int64(36)